name: Build

on:
  push:
  pull_request:

  # Run every friday
  schedule:
    - cron: 1 12 * * 5

env:
  BUILD_TYPE: Release
  # For macOS qt keg-only package
  CMAKE_PREFIX_PATH: '/usr/local/opt/qt@5'

jobs:
  build:
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-20.04', 'ubuntu-18.04']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies (macOS)
      run: brew install fftw liquid-dsp qt@5
      if: matrix.os == 'macos-latest'

    - name: Install dependencies (Ubuntu)
      run: sudo apt install libfftw3-dev libliquid-dev qtbase5-dev
      if: startsWith(matrix.os, 'ubuntu-')

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

